# Generated by Django 4.0.4 on 2022-07-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promociones',
            fields=[
                ('idPromocion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id promocion')),
                ('descuento', models.IntegerField(verbose_name='descuento')),
            ],
        ),
    ]
