# Generated by Django 4.0.4 on 2022-07-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_promociones'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiciletaArriendo',
            fields=[
                ('idBicileta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de bicicleta')),
                ('nombreBicileta', models.CharField(max_length=50, verbose_name='Nombre del bicicleta')),
                ('descripcionBicileta', models.CharField(max_length=50, verbose_name='Descripcion de bicicleta')),
                ('precioProducto', models.IntegerField(verbose_name='Precio de bicicleta')),
                ('imagen', models.ImageField(default=None, null=True, upload_to='producto')),
                ('stock', models.IntegerField(default=None, null=True, verbose_name='Stock')),
            ],
        ),
    ]
