# Generated by Django 4.0.5 on 2022-06-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_idusuario'),
    ]

