# Generated by Django 3.2.13 on 2022-06-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('idReparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id reparacion')),
                ('fechaReparacion', models.DateField(verbose_name='Fecha reparacion')),
                ('tipoReparacion', models.CharField(max_length=50, verbose_name='Tipo reparacion')),
                ('detalleReparacion', models.TextField(max_length=500, verbose_name='Detalle reparacion')),
                ('valorReparacion', models.IntegerField(verbose_name='Valor reparacion')),
                ('estado', models.CharField(default=None, max_length=50, null=True, verbose_name='Estado')),
                ('fechaEstado', models.DateField(default=None, null=True, verbose_name='Fecha actualizacion estado')),
            ],
        ),
    ]
