# Generated by Django 3.2.13 on 2022-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=None, null=True, verbose_name='Stock'),
        ),
    ]
