# Generated by Django 3.2.13 on 2022-07-01 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTipoArriendo',
            fields=[
                ('idTipoArriendo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo arriendo')),
                ('descripTipoArriendo', models.CharField(max_length=100, verbose_name='Descripcion tipo arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTipoBicicleta',
            fields=[
                ('idTipoBicicleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo bicicleta')),
                ('descripTipoBicicleta', models.CharField(max_length=100, verbose_name='Descripcion tipo bicicleta')),
            ],
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='tipoArriendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typetipoarriendo', verbose_name='Tipo arriendo'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='tipoBicicleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typetipobicicleta', verbose_name='Tipo bicicleta'),
        ),
    ]
