# Generated by Django 3.2.13 on 2022-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReparaciones',
            fields=[
                ('idTipoReparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo reparacion')),
                ('descripReparacion', models.CharField(max_length=100, verbose_name='Descripcion reparacion')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTipoArriendo',
            fields=[
                ('idTipoArriendo', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo arriendo')),
                ('descripTipoArriendo', models.CharField(max_length=100, verbose_name='Descripcion tipo arriendo')),
            ],
        ),
        migrations.CreateModel(
            name='TypeTipoBicicleta',
            fields=[
                ('idTipoBicicleta', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo bicicleta')),
                ('descripTipoBicicleta', models.CharField(max_length=100, verbose_name='Descripcion tipo bicicleta')),
            ],
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='tipoArriendo',
            field=models.CharField(max_length=200, verbose_name='Tipo arriendo'),
        ),
        migrations.AlterField(
            model_name='arriendo',
            name='tipoBicicleta',
            field=models.CharField(max_length=200, verbose_name='Tipo bicicleta'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='tipoReparacion',
            field=models.CharField(max_length=200, verbose_name='Tipo reparacion'),
        ),
    ]
