# Generated by Django 3.2.13 on 2022-07-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220701_0041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeReparaciones',
            fields=[
                ('idTipoReparacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id tipo reparacion')),
                ('descripReparacion', models.CharField(max_length=100, verbose_name='Descripcion reparacion')),
            ],
        ),
    ]
