# Generated by Django 3.2.13 on 2022-07-02 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220701_0231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeReparaciones',
        ),
        migrations.DeleteModel(
            name='TypeTipoArriendo',
        ),
        migrations.DeleteModel(
            name='TypeTipoBicicleta',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='abonoUSDvalorArriendo',
            field=models.IntegerField(default=django.utils.timezone.now, verbose_name='AbonoUSD valor arriendo'),
            preserve_default=False,
        ),
    ]
