# Generated by Django 4.0.4 on 2022-07-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220701_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='abonoUSDvalorArriendo',
            field=models.IntegerField(default=None, null=True, verbose_name='AbonoUSD valor arriendo'),
        ),
    ]
