# Generated by Django 3.2.13 on 2022-07-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220701_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendo',
            name='abonoUSDvalorArriendo',
            field=models.IntegerField(default=None, null=True, verbose_name='AbonoUSD valor arriendo'),
        ),
    ]
