# Generated by Django 3.2.13 on 2022-07-01 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_typereparaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='tipoReparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typereparaciones', verbose_name='Tipo reparacion'),
        ),
    ]
