# Generated by Django 3.2.13 on 2022-07-02 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_arriendo_estadoarriendo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='estadoArriendo',
        ),
    ]
