# Generated by Django 3.2.13 on 2022-07-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_arriendo_estadoarriendo'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='estadoArriendo',
            field=models.CharField(max_length=50, null=True, verbose_name='Estado Arriendo'),
        ),
    ]
