# Generated by Django 3.2.13 on 2022-07-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_biciletaarriendo'),
        ('core', '0024_arriendo_estadoarriendo'),
    ]

    operations = [
    ]
