# Generated by Django 4.0.5 on 2022-06-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_producto_precioproducto'),
    ]

    operations = [
        
    ]
