# Generated by Django 4.0.4 on 2022-06-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_categoria_producto_categoria_id'),
    ]


