# Generated by Django 4.0.5 on 2022-06-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
       
    ]
